Feature/contributing
Mesh4all/m4ag-firmware pull request #8
Opened 2021-11-11 18:32 UTC by eduazocar

### Contribution description

### Testing procedure

### Issues/PRs references

2021-11-11 20:25 UTC, luisan00 commented on CONTRIBUTING.md
> +3. Install RIOT-OS.
Already it's  instaled as submodule so this step is unnecessary

2021-11-12 21:38 UTC, luisan00 requested changes

2021-11-12 21:38 UTC, luisan00 commented on CONTRIBUTING.md
> +- ### <a href="#titlecc"> Contributing Code</a>
Don't use heading marks in this list

2021-11-12 21:38 UTC, luisan00 commented on CONTRIBUTING.md
> +### **1. Clonning**
Don't use bold syntax here, h3 heading is enough

2021-11-12 21:38 UTC, luisan00 commented on CONTRIBUTING.md
> +### **2. Updating Submodules**
Same here

2021-11-12 21:38 UTC, luisan00 commented on CONTRIBUTING.md
> +### Thank you very much for your future contribution, we are now connected together in this great mesh around the world!!!.
Don't use here H3, I think it's better bold or none, simple text

2021-11-12 21:38 UTC, luisan00 commented on CONTRIBUTING.md
> +Our firmware is based on RIOT-OS, so you have to apply updates from the RIOT repository within the m4ag firmware using the following command lines with git.
link to RIOT-OS repo in the first mention

2021-11-12 21:38 UTC, luisan00 commented on CONTRIBUTING.md
> +if you are starting work with mesh4all, you can read our documentation, and you will know all supported boards, and resources.
.. starting **to** work...

2021-11-13 21:03 UTC, luisan00 commented
Now looks good @eduazocar , please do squash with all commits before to merge and set the commit msg to `docs: add contributing guidelines` or something like that but, important precede `docs:`
Do: `git rebase -i main`

2021-11-14 05:03 UTC, eduazocar commented
Don't pay attention to all the attempts of merge xD, I forgot when i changed the README.md for some tests

2021-11-14 05:08 UTC, eduazocar commented
Don't pay attention to all the attempts of merge, I forgot when i changed the README.md for some test

2021-11-14 07:55 UTC, luisan00 commented
Looks good @eduazocar, go abead

2021-11-14 07:55 UTC, luisan00 approved these changes

2021-11-14 07:59 UTC, merged